version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "danilokorber" # Replace with your GitHub username
    assignees:
      - "danilokorber" # Replace with your GitHub username
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated-pr"
    milestone: 2 # Replace with your milestone number if using milestones

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    reviewers:
      - "danilokorber" # Replace with your GitHub username
    assignees:
      - "danilokorber" # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated-pr"

  # Note: Since Phone Forge has no dependencies in package.json,
  # the npm updates will primarily monitor for new Node.js versions
  # and any dev dependencies you might add in the future
