name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy homepage files
        run: |
          cp index.html docs/
          # Copy any additional assets if they exist
          if [ -d "assets" ]; then
            cp -r assets docs/
          fi
          if [ -d "images" ]; then
            cp -r images docs/
          fi

      - name: Generate sitemap
        run: |
          cat > docs/sitemap.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://easyware-io.github.io/phone-forge/</loc>
              <lastmod>$(date +%Y-%m-%d)</lastmod>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
          </urlset>
          EOF

      - name: Generate robots.txt
        run: |
          cat > docs/robots.txt << 'EOF'
          User-agent: *
          Allow: /

          Sitemap: https://easyware-io.github.io/phone-forge/sitemap.xml
          EOF

      - name: Generate 404 page
        run: |
          cat > docs/404.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>404 - Page Not Found | Phone Forge</title>
              <style>
                  body {
                      font-family: 'Inter', sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      min-height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #2563eb 0%, #06b6d4 100%);
                      color: white;
                      text-align: center;
                  }
                  .container {
                      max-width: 500px;
                      padding: 2rem;
                  }
                  h1 {
                      font-size: 6rem;
                      margin: 0;
                      opacity: 0.8;
                  }
                  h2 {
                      font-size: 2rem;
                      margin: 1rem 0;
                  }
                  p {
                      font-size: 1.1rem;
                      margin-bottom: 2rem;
                      opacity: 0.9;
                  }
                  .btn {
                      display: inline-block;
                      padding: 12px 24px;
                      background: white;
                      color: #2563eb;
                      text-decoration: none;
                      border-radius: 8px;
                      font-weight: 500;
                      transition: transform 0.3s;
                  }
                  .btn:hover {
                      transform: translateY(-2px);
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>404</h1>
                  <h2>📱 Page Not Found</h2>
                  <p>The page you're looking for doesn't exist, but Phone Forge is still here to help with all your phone number needs!</p>
                  <a href="/" class="btn">🏠 Go Home</a>
              </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Verify deployment
        run: |
          echo "🎉 Website deployed successfully!"
          echo "🔗 URL: ${{ steps.deployment.outputs.page_url }}"

          # Wait a moment for deployment to propagate
          sleep 30

          # Test if the site is accessible
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ steps.deployment.outputs.page_url }}")
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "✅ Website is accessible and returning HTTP 200"
          else
            echo "⚠️ Website returned HTTP $HTTP_STATUS"
          fi
